version: "3.9"
services:
    rabbitmq:
        build: ./rabbitmq
        ports:
            - 15672:15672

    syslog:
        image: balabit/syslog-ng

    producer:
        build:
            context: .
            dockerfile: ./producer/Dockerfile
        depends_on:
            - rabbitmq
        volumes:
            - ./producer:/opt/producer

    consumer:
        build:
            context: .
            dockerfile: ./consumer/Dockerfile
        depends_on:
            - rabbitmq
            - producer
        volumes:
            - ./consumer:/opt/consumer

